# Generated by Django 4.2.1 on 2023-09-10 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='tic_fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tic_hora',
            field=models.TimeField(),
        ),
    ]
