# Generated by Django 4.2.1 on 2023-09-09 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('des_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('des_nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('prop_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('prop_nombre', models.CharField(max_length=50)),
                ('prop_apellidos', models.CharField(blank=True, max_length=50)),
                ('prop_licencia', models.CharField(max_length=100)),
                ('prop_categoria', models.CharField(max_length=20)),
                ('prop_fecha_revalidacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('tar_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('tar_tarifa', models.IntegerField()),
                ('tar_nro_asientos', models.IntegerField()),
                ('tar_categoria', models.CharField(max_length=3)),
                ('tar_destino', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('veh_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('veh_placa', models.CharField(max_length=50)),
                ('veh_categoria', models.CharField(max_length=3)),
                ('veh_marca', models.CharField(max_length=50)),
                ('veh_modelo', models.CharField(max_length=50)),
                ('veh_anio_fabricacion', models.IntegerField()),
                ('veh_nro_asientos', models.IntegerField()),
                ('veh_destino', models.ForeignKey(db_column='veh_destino', on_delete=django.db.models.deletion.CASCADE, to='travels_app.destination')),
                ('veh_propietario', models.ForeignKey(db_column='veh_propietario', on_delete=django.db.models.deletion.CASCADE, to='travels_app.owner')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('user_nombre', models.CharField(max_length=20)),
                ('user_apellidos', models.CharField(max_length=20)),
                ('user_email', models.CharField(max_length=30)),
                ('user_password', models.CharField(max_length=20)),
                ('user_role', models.ForeignKey(db_column='user_role', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='travels_app.role')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('tic_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('tic_fecha', models.DateField(auto_now=True)),
                ('tic_hora', models.TimeField(auto_now=True)),
                ('tic_tarifa', models.ForeignKey(db_column='tic_tarifa', on_delete=django.db.models.deletion.DO_NOTHING, to='travels_app.tarifa')),
                ('tic_vehiculo', models.ForeignKey(db_column='tic_vehiculo', on_delete=django.db.models.deletion.DO_NOTHING, to='travels_app.vehicule')),
            ],
        ),
    ]
