# Generated by Django 4.2.3 on 2023-07-13 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('prop_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('prop_nombre', models.CharField(max_length=50)),
                ('prop_fechaNacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('veh_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('veh_placa', models.CharField(max_length=50)),
                ('veh_marca', models.CharField(max_length=50)),
                ('veh_modelo', models.CharField(max_length=50)),
                ('veh_nro_asientos', models.IntegerField()),
                ('veh_propietario', models.ForeignKey(db_column='veh_propietario', on_delete=django.db.models.deletion.DO_NOTHING, to='travels_app.propietario')),
            ],
        ),
    ]
