# Generated by Django 4.2.1 on 2023-08-07 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels_app', '0007_tarifa_user_alter_vehicule_veh_categoria_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='tic_tarifa',
            field=models.ForeignKey(db_column='tic_tarifa', on_delete=django.db.models.deletion.CASCADE, to='travels_app.tarifa'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tic_vehiculo',
            field=models.ForeignKey(db_column='tic_vehiculo', on_delete=django.db.models.deletion.CASCADE, to='travels_app.vehicule'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='veh_destino',
            field=models.ForeignKey(db_column='veh_destino', on_delete=django.db.models.deletion.CASCADE, to='travels_app.destination'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='veh_propietario',
            field=models.ForeignKey(db_column='veh_propietario', on_delete=django.db.models.deletion.CASCADE, to='travels_app.owner'),
        ),
    ]
