# Generated by Django 4.2.1 on 2023-08-25 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels_app', '0008_alter_ticket_tic_tarifa_alter_ticket_tic_vehiculo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='tic_tarifa',
            field=models.ForeignKey(db_column='tic_tarifa', on_delete=django.db.models.deletion.DO_NOTHING, to='travels_app.tarifa'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tic_vehiculo',
            field=models.ForeignKey(db_column='tic_vehiculo', on_delete=django.db.models.deletion.DO_NOTHING, to='travels_app.vehicule'),
        ),
    ]
