# Generated by Django 4.2.1 on 2023-08-26 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels_app', '0009_alter_ticket_tic_tarifa_alter_ticket_tic_vehiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.ForeignKey(db_column='user_role', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='travels_app.role'),
        ),
    ]
